var gulp = require('gulp');
var browserify = require('gulp-browserify');
var less = require('gulp-less');
var rt = require('gulp-react-templates');
var path = require('path');
var fs = require('fs');

gulp.task('rt', function() {
  gulp.src('app/components/**/*.rt')
    .pipe(rt({ modules: 'commonjs', format: 'stylish' }))
    .pipe(gulp.dest('app/components/'));
});

gulp.task('scripts', function() {
  gulp.src(['app/main.js'])
    .pipe(browserify({
        debug: true,
        transform: [ 'reactify' ]
    }))
    .pipe(gulp.dest('public/'));
});

gulp.task('widgets', function() {
  // List the widgets to additional JS file
  var WIDGET_PATH = 'app/components/widgets/';
  var WIDGET_FILE = 'Widgets.js';

  var normalizedPath = path.join(__dirname, WIDGET_PATH);
  var requires = '/* Warning! This file is generated by Gulp. */\n';

  requires += 'module.exports = {\n';
  fs.readdirSync(normalizedPath).forEach(function(file) {
    if (file === WIDGET_FILE)
      return;

    var jsFile = file + '/' + file;
    requires += '\t'+ file +': require(\'./'+ jsFile +'\'),\n';
  });
  requires += '};';

  fs.writeFile(WIDGET_PATH + WIDGET_FILE, requires);
});

gulp.task('less', function() {
  gulp.src('app/less/main.less')
    .pipe(less({
      paths: [ path.join(__dirname, 'less', 'includes') ],
      compress: false
    }))
    .pipe(gulp.dest('public/'));
});

gulp.task('default', ['rt', 'widgets', 'scripts', 'less']);
