var gulp = require('gulp');
var browserify = require('gulp-browserify');
var less = require('gulp-less');
var rt = require('gulp-react-templates');
var browserSync = require('browser-sync').create();
var renderReact = require('./tools/gulp-render-react');
var path = require('path');
var fs = require('fs');

gulp.task('rt', function() {
  gulp.src('app/components/**/*.rt')
    .pipe(rt({ modules: 'commonjs', format: 'stylish' }))
    .pipe(gulp.dest('app/components/'));
});

gulp.task('scripts', function() {
  gulp.src(['app/main.js'])
    .pipe(browserify({
        debug: true,
        transform: [ 'babelify' ]
    }))
    .pipe(gulp.dest('public/'));
});

gulp.task('widgets', function() {
  // List the widgets to additional JS & Less files
  var WIDGET_PATH = 'app/components/widgets/';
  var WIDGET_FILE = 'Widgets.js';
  var LESS_FILE = 'widgets.less';

  var normalizedPath = path.join(__dirname, WIDGET_PATH);
  var note = '/* Note! This file is generated by Gulp. */\n';

  var less = note;
  var js = note;
  js += 'module.exports = {\n';
  fs.readdirSync(normalizedPath).forEach(function(file) {
    if (file === WIDGET_FILE)
      return;

    // TODO Check that file exists
    var widgetFile = file + '/' + file;
    js += '\t'+ file +': require(\'./'+ widgetFile +'\'),\n';
    less += "@import '../components/widgets/"+widgetFile+"';\n";
  });
  js += '};';

  fs.writeFile(WIDGET_PATH + WIDGET_FILE, js);
  fs.writeFile('app/less/' + LESS_FILE, less);
});

gulp.task('less', function() {
  gulp.src('app/less/main.less')
    .pipe(less({
      paths: [ path.join(__dirname, 'less', 'includes') ],
      compress: false
    }))
    .pipe(gulp.dest('public/'));
});

gulp.task('html', function() {
  gulp.src('app/index.html')
    .pipe(renderReact())
    .pipe(gulp.dest('public/'));
});

gulp.task('static', function() {
  gulp.src('app/images/*').pipe(gulp.dest('public/images/'));
});

// Browsersync server
gulp.task('serve', function() {
    browserSync.init({
        server: "public/"
    });

    gulp.watch('app/*.html', ['html', 'static']);
    gulp.watch('app/**/*.js', ['scripts']);
    gulp.watch('app/**/*.rt', ['rt']);
    gulp.watch('app/**/*.less', ['less']);

    gulp.watch('public/*').on('change', browserSync.reload);
});

gulp.task('default', ['rt', 'widgets', 'scripts', 'less', 'html', 'static']);
